<label for="<?= $this->getFieldId('taxvat')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Tax/VAT number') ?></label>
<div class="input-box">
    <input type="text" id="<?= $this->getFieldId('taxvat')?>" name="<?php echo $this->getFieldName('taxvat')?>" value="<?php echo $this->escapeHtml($this->getTaxvat()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Tax/VAT number')) ?>" class="input-text validar-cpf <?php echo $this->helper('customer/address')->getAttributeValidationClass('taxvat') ?>" <?php echo $this->getFieldParams() ?> />
</div>

<script type="text/javascript">
//<![CDATA[
    Validation.add('validar-cpf', '<?= $this->__('O número informado é inválido') ?>', function(v) {return validaCPFCNPJ.init(v,0);});
    document.observe("dom:loaded",() => {
        document.querySelectorAll('#<?= $this->getFieldId('taxvat')?>').forEach(($input) => {
            $input.addEventListener('input', (e) => {
                e.target.value = validaCPFCNPJ.mask(e.target.value);
            }, false)
        });
    })

//]]>
</script>
